# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c

branches:
 only:
 - master

install:
    - gem install cocoapods -v 0.38.2 --no-document

before_script:
    - cd Example
    - pod install

xcode_workspace: NumberMorphView.xcworkspace
xcode_scheme: NumberMorphView-Example
xcode_sdk: iphonesimulator9.2
